name: Validate One Click Apps

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14]
        steps:
            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache .pnpm-store
              uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Install pnpm
              run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
            - name: Run Validate and Formatter
              run: pnpm i && pnpm run validate_apps && pnpm run formatter
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
